services:
  service-api:
    build:
      context: .
      dockerfile: service.Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    volumes:
      - files_agents:/app/agents
      - .:/app:ro
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
  agent-api:
    build:
      context: .
      dockerfile: agents/agents.Dockerfile
    command: adk web
    ports:
      - "8000:8000"
    volumes:
      - files_agents:/app/agents:ro
      - .:/app:ro
    environment:
      - PYTHONUNBUFFERED=1
    env_file  :
      - .env

volumes:
  files_agents:
