name: Build Docker image on push

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and tag Docker image with branch name
        env:
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          BRANCH: ${{ github.ref_name }}
        run: |
          docker build -t ghcr.io/${GHCR_USERNAME}/adk-starter:${BRANCH} .

      - name: Push Docker image
        env:
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          BRANCH: ${{ github.ref_name }}
        run: |
          docker push ghcr.io/${GHCR_USERNAME}/adk-starter:${BRANCH}
