name: Build and Push Unified Docker Image

on:
  push:
    branches: ['**']
    paths:
      - 'docker-compose.prod.yml'
      - 'Dockerfile.unified'
      - 'supervisord.conf'
      - 'entrypoint.sh'
      - '.github/workflows/docker-build-unified.yml'

jobs:
  build-and-push-unified:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME || github.actor }}
          password: ${{ secrets.CR_PAT || github.token }}

      - name: Set up environment
        id: env
        run: |
          # Clean up branch name for use in tags
          BRANCH_NAME=$(echo ${{ github.ref_name }} | tr '/' '-')
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME || github.actor }}/adk-starter-unified" >> $GITHUB_ENV
          echo "IMAGE_TAG=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Build and push unified image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.unified
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Output image information
        run: |
          echo "Successfully built and pushed unified image:"
          echo "- ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
